apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel
  labels:
    app: hotel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hotel
  template:
    metadata:
      labels:
        app: hotel
    spec:
      containers:
        - name: hotel-container
          image: hotel-service-portal:1.1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
